linters:
  enable-all: true
  disable:
  # Dont care:
  - exhaustruct
  - depguard
  - wrapcheck
  - tagalign
  - forbidigo
  - perfsprint
  - gochecknoglobals
  - tenv  # deprecated, use usetesting

issues:
  exclude-rules: []
